# Configuración postgreSQL
spring:  
  jpa:  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/BootCampInfierno"  
    username: belazar  
    password: belazar13
